http {
    server {
        listen 4040 default_server;
        listen [::]:4040 default_server;
        server_name _;
        root ./build;
        autoindex on;

        location /sqwerl/ {
            proxy_pass http://localhost:6719/;
        }
    }
}

events {
}